export AWS_ACCESS_KEY_ID="REPLACE"
export AWS_SECRET_ACCESS_KEY="REPLACE"

# the following settings are for the CIAM-Non-Prod account
export DEFAULT_REGION_NAME="REPLACE"
export DEFAULT_VPC_ID="REPLACE"
export DEFAULT_AMI_ID="REPLACE"
export DEFAULT_SUBNET_ID="REPLACE"
export DEFAULT_INSTANCE_TYPE="REPLACE"
export DEFAULT_AMI_NAME="REPLACE"
